### ISSUE TITLE
Issue when installing the module

### ISSUE THREAD

**Issue by acolinwmc** [jdanthinne/advancedfeaturesvalues#20]
I upload the module through my ftp client, then I went into my module list, and when I try to instal it I get an error message: 

[PrestaShop] Fatal error in module file :/home/www/1af0eb0e938adb9b3f0e370ba590895f/web/presta15/classes/module/Module.php:
Uncaught exception 'ReflectionException' with message 'Class FeatureValueOverrideOriginal_remove5668448375837 does not exist' in /home/www/1af0eb0e938adb9b3f0e370ba590895f/web/presta15/classes/module/Module.php:2638 Stack trace: #0 /home/www/1af0eb0e938adb9b3f0e370ba590895f/web/presta15/classes/module/Module.php(2638): ReflectionClass->__construct('FeatureValueOve...') #1 /home/www/1af0eb0e938adb9b3f0e370ba590895f/web/presta15/classes/module/Module.php(2482): ModuleCore->removeOverride('FeatureValue') #2 /home/www/1af0eb0e938adb9b3f0e370ba590895f/web/presta15/classes/module/Module.php(287): ModuleCore->uninstallOverrides() #3 /home/www/1af0eb0e938adb9b3f0e370ba590895f/web/presta15/modules/advancedfeaturesvalues/advancedfeaturesvalues.php(51): ModuleCore->install() #4 /home/www/1af0eb0e938adb9b3f0e370ba590895f/web/presta15/controllers/admin/AdminModulesController.php(846): AdvancedFeaturesValues->install() #5 /home/www/1af0eb0e938adb9b3f0e370ba590895f/web/presta15/controllers/admin/AdminModulesController.php(1

Do you have any clue?

thanks !

**Comment by RaphGC** [comment]
I have the same issue (prestashop 1.6.1.6), did you have any answer ?

**Comment by RaphGC** [comment]
I'm on PHP 5.4, reading other issues, I think it may come from this, any solution ?
